### ISSUE TITLE
WIP – Song snippets

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#1]
## Value statement - a requirement, not a solution

As a **music enthusiast**
I need **to listen to a lot of various songs**
so that **I easily discover new bands and artists.**

## Description
![20201115_UserStory_01](https://user-images.githubusercontent.com/71657539/99183988-3d041500-2740-11eb-9309-13597f180437.jpg)

## Acceptance criteria

- [ ] A song snippet plays automatically.
- [ ] The song cover (image), artist and song title are always visible.

## Tasks

- [ ] Create feature branch
- [ ] Create a SongSnippet component in Styleguidist
- [ ] Add necessary styling
- [ ] Write component tests
- [ ] Add component to app

## Size
medium
