### ISSUE TITLE
Confirming deletion

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#15]
## Value statement 

As a **music enthusiast**
I need **a security mechanism when deleting my favorites**
so that **I don't accidentally delete a song that I want to keep.**

## Description
![20201129_Gesellenstueck_Wireframes_07](https://user-images.githubusercontent.com/71657539/100551185-6912b080-327f-11eb-9750-e98a11d22dc0.jpg)

## Acceptance criteria

- [ ] By clicking the delete button, the icon changes its appearance to an arrow
- [ ] By clicking the delete button, the song content and play button disappears
- [ ] By clicking the delete button, a new text is displayed
- [ ] By clicking the reset button, the previous state is restored
- [ ] If the reset button is not clicked, the song is no longer visible during the reload

## Tasks

- [ ] Create feature branch
- [ ] Add state "toBeDeleted"
- [ ] Add reset logic
- [ ] Fix bug: song stops playing by clicking the delete button
- [ ] Add necessary styling
- [ ] Write component tests

## Size
small
