### ISSUE TITLE
Express server

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#16]
## Value statement

As a **music enthusiast**
I need **a huge list of songs and artists**
so that **I can discover even more artists.**

## Description
![20201129_Gesellenstueck_Wireframes_08](https://user-images.githubusercontent.com/71657539/100551560-b263ff80-3281-11eb-8b57-075732ce1aef.jpg)

## Acceptance criteria

- [ ] Access token not accessible in the frontend

## Tasks

- [ ] Add Express.js server
- [ ] Create feature branch
- [ ] Add fetch logic
- [ ] Write fecthMock tests

## Size
large
