### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#17]
## Value statement 

As a **music enthusiast**
I need **a notification if the music cannot be loaded**
so that **I know how I can continue to use the app.**

## Description
![20201129_Gesellenstueck_Wireframes_09](https://user-images.githubusercontent.com/71657539/100551668-78dfc400-3282-11eb-9367-8165cc362135.jpg)

## Acceptance criteria

- [ ] If no data is loaded, the error message becomes visible

## Tasks

- [ ] Create feature branch
- [ ] Create ErrorMessage component in Styleguidist
- [ ] Add hasError logic
- [ ] Add necessary styling
- [ ] Write component tests
- [ ] Add component to app

## Size
medium
