### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#18]
## Value statement

As a **music enthusiast**
I need **an introduction to the content**
so that **I have a better overview of where I am in the app.**

## Description
![20201129_Gesellenstueck_Wireframes_10](https://user-images.githubusercontent.com/71657539/100552485-c874be80-3287-11eb-9c17-37a624c6eaf8.jpg)

## Acceptance criteria

- [ ] The header text is an introduction to the visible content
- [ ] The user can't interact with the header

## Tasks

- [ ] Create feature branch
- [ ] Create Header component in Styleguidist
- [ ] Match the styling to the design
- [ ] Update file structure
- [ ] Write component tests

## Size
medium
