### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#19]
## Value statement

As a **music enthusiast**
I need **quick way to switch pages**
so that **I can get the content I want faster.**

## Description
![20201129_Gesellenstueck_Wireframes_11](https://user-images.githubusercontent.com/71657539/100552680-e7c01b80-3288-11eb-98eb-401795030f16.jpg)

## Acceptance criteria

- [ ] The active icon is connected to the page the user is on
- [ ] Clicking the active icon does not change anything
- [ ] Clicking the inactive icon changes the pages 
- [ ] Clicking the inactive icon changes the appearance of both icons

## Tasks

- [ ] Create feature branch
- [ ] Add react-router-dom 
- [ ] Restructure the files
- [ ] Add page files
- [ ] Add components to pages

## Size
medium
