### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#2]
## Value statement - a requirement, not a solution

As a **music enthusiast**
I need **to be able to see how long the song is playing and to pause it**
so that **I can focus on the song.**

## Description
![20201115_UserStory_02](https://user-images.githubusercontent.com/71657539/99184712-39bf5800-2745-11eb-8b8e-e838722c6103.jpg)

## Acceptance criteria

- [ ] The timer and pause button are always visible.
- [ ] The remaining time is shown as a number next to the timer.
- [ ] The timer is animated.
- [ ] When the pause Button is activated, it changes its appearance.

## Tasks

- [ ] Create feature branch
- [ ] Create a Timer component in Styleguidist
- [ ] Add necessary styling
- [ ] Write component tests
- [ ] Add component to SongSnippet

## Size
medium
