### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#24]
## Value statement 

As a **music enthusiast**
I need **login with my spotify account**
so that **the complete library of songs is available to me.**

## Description
![20201207_Gesellenstueck_Wireframes_13](https://user-images.githubusercontent.com/71657539/101463433-b35df680-393d-11eb-92a3-46550fc82106.jpg)

## Acceptance criteria

- [ ] The login page is visible, if there ist no token
- [ ] By clicking the login button the user will be redirect to spotify authorization

## Tasks

- [ ] Create feature branch
- [ ] Create Login component
- [ ] Add styling
- [ ] Write component tests
- [ ] Add component to app

## Size
small
