### ISSUE TITLE
Random song

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#25]
## Description
![20201207_Gesellenstueck_Wireframes_14](https://user-images.githubusercontent.com/71657539/101463825-354e1f80-393e-11eb-8254-2c128dd2924e.jpg)

## Acceptance criteria

- [ ] The home page shows random songs
- [ ] With every reload the page shows new songs

## Tasks

- [ ] Create feature branch
- [ ] Fetch songs from Spotify API
- [ ] Write fetchMock tests

## Size
medium
