### ISSUE TITLE
Skip song

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#26]
## Value statement

As a **music enthusiast**
I need **to skip songs that I don't like**
so that **I can discover music I like faster.**

## Description
![20201207_Gesellenstueck_Wireframes_15](https://user-images.githubusercontent.com/71657539/101464495-008e9800-393f-11eb-83c7-766dbe642188.jpg)

## Acceptance criteria

- [ ] Only one song at a time is visible
- [ ] By skipping or saving a song, the next one will be rendered 
- [ ] A skipped song won't be saved 

## Tasks

- [ ] Create feature branch
- [ ] Add skip button to artist
- [ ] Add skip logic
- [ ] Update save logic

## Size
medium
