### ISSUE TITLE
WIP – Save & skip

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#3]
## Value statement - a requirement, not a solution

As a **music enthusiast**
I need **to separate the songs I like from the songs I don't**
so that **I can quickly find the ones that I liked.**

## Description
![20201115_UserStory_03](https://user-images.githubusercontent.com/71657539/99185222-c3bcf000-2748-11eb-8ae5-c4030f67ee19.jpg)

## Acceptance criteria

- [ ] The save and skip buttons are always visible.
- [ ] When the save button is activated (by click), it changes its appearance.
- [ ] When the skip button was clicked, the next song starts to play.

## Tasks

- [ ] Create feature branch
- [ ] Create a Button component in Styleguidist
- [ ] Add save logic
- [ ] Add skip logic
- [ ] Add necessary styling
- [ ] Write component tests
- [ ] Add component to SongSnippet

## Size
medium
