### ISSUE TITLE
WIP – Bookmark overview

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#4]
## Value statement - a requirement, not a solution

As a **music enthusiast**
I need **a way to just see the songs I've saved**
so that **I have an overview of the artists I like.**

## Description
![20201115_UserStory_04](https://user-images.githubusercontent.com/71657539/99186477-d2a7a080-2750-11eb-9f89-78b5cb0cf88a.jpg)

## Acceptance criteria

- [ ] The link button toggles.
- [ ] The cover, song title and artist are shown in a list.
- [ ] The last song saved is at the top of the list.

## Tasks

- [ ] Create feature branch
- [ ] Create Link component
- [ ] Create a BookmarkOverview component
- [ ] Add state "isBookmarked"
- [ ] Add necessary styling
- [ ] Write component tests

## Size
medium
