### ISSUE TITLE
Save & load locally

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#5]
## Value statement - a requirement, not a solution

As a **music enthusiast**
I need **my bookmarks even after a reload or restart**
so that **I don't loose my valuable customizations.**

## Description
- No new visual content

## Acceptance criteria

- [ ] Every change on the state "isBookmarked" should trigger a save to localStorage.
- [ ] Reload of the page should load "isBookmarked" from localStorage.

## Tasks

- [ ] Create feature branch
- [ ] Create services for localStorage
- [ ] Implement save/load for "isBookmarked"
- [ ] Test on mobile device (differnet browser)

## Size
medium
