### ISSUE TITLE
Artist list

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#6]
## Value statement

As a **music enthusiast**
I need **a list of artists and their most popular songs**
so that **I get inspired and can easily discover new music.**

## Description
![20201116_Gesellenstueck_Wireframes_01](https://user-images.githubusercontent.com/71657539/99253734-91c39080-2811-11eb-8f8b-c8e18d0436b9.jpg)

## Acceptance criteria

- [ ] A list entry consists of the artist name and song
- [ ] The user can't interact with the list

## Tasks

- [ ] Create feature branch
- [ ] Save a list of artists and songs as .json using the spotify API
- [ ] Create ArtistList component in Styleguidist
- [ ] Add necessary styling
- [ ] Write component tests
- [ ] Add component to app

## Size
medium
