### ISSUE TITLE
Play song

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#7]
## Value statement

As a **music enthusiast**
I need **to listen to a song of an artist**
so that **I get an impression of the music.**

## Description
![20201116_Gesellenstueck_Wireframes_02](https://user-images.githubusercontent.com/71657539/99255220-e536de00-2813-11eb-85b8-6dfa001ef2f8.jpg)

## Acceptance criteria

- [ ] The button changes its appearance by click
- [ ] By click a song snippet starts to play
- [ ] The song pauses when the button is clicked again
- [ ] The song will play for 15 seconds if not paused
- [ ]  When the song is finished, the button will automatically change its appearance

## Tasks

- [ ] Create feature branch
- [ ] Add audio data to the list of artists and songs using the spotify API
- [ ] Create AudioButton component in Styleguidist
- [ ] Add necessary styling
- [ ] Write component tests
- [ ] Add component to app

## Size
medium
