### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#8]
## Value statement

As a **music enthusiast**
I need **to save the songs that I like**
so that **I can find them again later and listen to them again.**

## Description
![20201116_Gesellenstueck_Wireframes_03](https://user-images.githubusercontent.com/71657539/99257169-df8ec780-2816-11eb-8e91-d7249be33050.jpg)

## Acceptance criteria

- [ ] The "save" button changes its appearance by click (toggle)
- [ ] By click on the "saved songs" button only the list of saved songs is visible
- [ ] By click on the "saved songs" button the text changes to "all songs"
- [ ] By click on the "all songs" button the full list of artists and songs is visible
- [ ] By click on the "all songs" button the text changes to "saved songs"
- [ ] The last song saved is at the top of the list

## Tasks

- [ ] Create feature branch
- [ ] Create Button component in Styleguidist
- [ ] Create Link component in Styleguidist
- [ ] Add state "isBookmarked"
- [ ] Add bookmark logic
- [ ] Add necessary styling
- [ ] Write component tests
- [ ] Add component to app

## Size
large
