### ISSUE TITLE
Remove bookmark

### ISSUE THREAD

**Issue by ninapeters** [ninapeters/capstone-project#9]
## Value statement

As a **music enthusiast**
I need **the opportunity to remove an entry from my bookmarks**
so that **I can easily update my list of favorites.**

## Description
![20201116_Gesellenstueck_Wireframes_05](https://user-images.githubusercontent.com/71657539/99260282-76f61980-281b-11eb-95f4-4cececad6ce7.jpg)

## Acceptance criteria

- [ ] By click the entry disappears immediately
- [ ] The appearance of the "save" button (list of all artists) changes to default

## Tasks

- [ ] Create feature branch
- [ ] Create DeleteButton component in Styleguidist
- [ ] Add necessary styling
- [ ] Write component tests
- [ ] Add component to app

## Size
small
